### PR TITLE
feat: add support for export_evaluated_data_items_config in AutoMLTab…

### PR DESCRIPTION
**Pull request by geraint0923**
add support for export_evaluated_data_items_config in AutoMLTabularTrainingJob

### CODE REVIEW

**Review by sasha-gitg — APPROVED** [review]
LGTM!

**Comment by geraint0923** [comment]
Thanks! @sasha-gitg  Do you mind adding an `auto-merge` to this PR since I don't have the permission to merge in this repo?

**Comment by dparkar** [comment]
@sasha-gitg (Going by the the doc) Will this will only export it to a big query table ? Would it be possible to write a csv to cloud storage ? Or is there another work item planned for that ?

**Comment by geraint0923** [comment]
> @sasha-gitg (Going by the the doc) Will this will only export it to a big query table ? Would it be possible to write the predictions as a csv to cloud storage ? Or is there another work item planned for that ?

@dparkar Thanks for reaching out. We currently don't have a plan to support GCS output for this export feature since CSV doesn't have a straightforward support for the complex data types like array and struct.

**Pull request merged**
