### PR TITLE
export aiplatform_v1beta1 as aiplatform.gapic_v1beta1

### PR DESCRIPTION
**Pull request by dizcology**
*DO NOT MERGE* until confirmed about the approach.

Current user code (which will be broken after this change):
```
from google.cloud import aiplatform
dataset = aiplatform.Dataset(...)
```

Expected user code after this change:
```
from google.cloud.aiplatform import gapic_v1beta1
dataset = gapic_v1beta1.Dataset(...)
```
or 

```
from google.cloud import aiplatform
dataset = aiplatform.gapic_v1beta1.Dataset(...)
```

### CODE REVIEW

**Review by vinnysenthil — APPROVED** [review]

**Comment by vinnysenthil** [comment]
Namespace change has been LGTM'd

**Comment by busunkim96** [comment]
I'd prefer you actually create and put the code in that namespace. (i.e. move the code into `google/cloud/aiplatform/gapic`. There's a generator option to customize namespaces. (https://github.com/googleapis/googleapis/blob/b821f320473c8ec05a1c7fb9a496c958b1ab9834/google/devtools/clouderrorreporting/v1beta1/BUILD.bazel#L161)

Is the goal to split the generated layer from handwritten bits?

**Comment by vinnysenthil** [comment]
That is the goal, I'll let @dizcology follow up with a suggestion/decision.

**Comment by dizcology** [comment]
@software-dov could you point us to an example of setting namespace and name (https://github.com/googleapis/gapic-generator-python/blob/master/gapic/generator/options.py#L35-L36) through the GAPICMicrogenerator (https://github.com/googleapis/synthtool/blob/0762e8ee2ec21cdfc4d82020b985a104feb0453b/synthtool/gcp/gapic_microgenerator.py#L34)?

**Pull request merged**
