### PR TITLE
fix: 0 is now considered a valid step number in log_time_series_metrics

### LINKED ISSUE #3198: log_time_series_metrics doesn't handle step=0 correctly
OS: Debian 5.10.205-2 (2023-12-31) x86_64 GNU/Linux 
Python 3.10.13
pip 23.3.1
google-cloud-aiplatform: 1.37.0  

The experiment tracking (`python-aiplatform/google/cloud/aiplatform/metadata/experiment_run_resource.py`) contains the function `log_time_series_metrics` which accepts an optional `step` number. If this is not set (`step` has a falsy value), the step internally gets set to 1.

This is a problem if someone wants to log values for step 0 and 1 because both logs will be for step=1 and overwrite each other.

I am working on a PR to fix this: https://github.com/googleapis/python-aiplatform/pull/3199

### PR DESCRIPTION
**Pull request by simonhessner**
Fixes https://github.com/googleapis/python-aiplatform/issues/3198

Previously, when log_time_series_metrics is called without a step value it defaults to None. The function internally checked `if not step` and in this case, determined a step number. The problem is that 0 is falsy and therefore the function turns step=0 into step=1 which is a problem if the function is later called with step=1 (in that case the first logged values are overwritten)

Checking for `if step is None` fixes the problem.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-aiplatform/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)
- [ ] Get the necessary approvals
- [ ] Once the last commit on the PR has been approved, add the "ready to pull" label to the Pull Request

Note: do not merge your PR from GitHub. Adding the "ready to pull" label is the final step in the review process.
After approvals, the changes in your PR will be committed to the `main` branch and this PR will be closed.

Fixes #3198 🦕

### CODE REVIEW

**Comment by simonhessner** [comment]
@sasha-gitg Do you know why it continues to say "Some checks haven't completed yet" and "Waiting for status to be reported"?

**Review by ZhenyiQ — COMMENTED** [review]
This LGTM. @sasha-gitg ok if I approve?

**Review by lakeyk — APPROVED** [review]
Approved. Tested by running:
aiplatform.log_time_series_metrics(metrics=metrics, step=0)
aiplatform.log_time_series_metrics(metrics=metrics, step=1)
aiplatform.ExperimentRun.get(EXPERIMENT_RUN).get_time_series_data_frame()

And checking that the timeSeries data frame had entries for steps 0 and 1

**Comment by sasha-gitg** [comment]
> This LGTM. @sasha-gitg ok if I approve?

Good to go!

**Review by ZhenyiQ — APPROVED** [review]

**Comment by ZhenyiQ** [comment]
The change in the PR is committed to the main branch: https://github.com/googleapis/python-aiplatform/commit/fc214f5a66034fa9cd0bef8a5249547394983b48. Will close this PR. Thanks @simonhessner a lot for the contribution!

**Pull request closed without merging**
