### PR TITLE
fix: Fix FeatureStore and EntityTypes list methods

### LINKED ISSUE #1684: Fix FeatureStore list_entity_types() and EntityType list_features()
#### Environment details

  - OS type and version:
  - Python version: `3.7.12`
  - pip version: `22.2.2 `
  - `google-cloud-aiplatform` version: `1.16.1`

#### Steps to reproduce

I was trying to list the the EntityTypes and the Features created in a FeatureStore from Vertex AI Workbench (I've already detailed the Environment details). The region I built the FeatureStore into is `europe-west4`, son when I try to list the entities and the features it keeps failing (more details in the Stack Trace and Code Example).

#### Code example

```python
PROJECT_ID = "my-project"
REGION = "europe-west4"
FEATURESTORE_ID = "my_feature_store_id"

fs = FeaturestoreCustom(
    featurestore_name=FEATURESTORE_ID,
    project=PROJECT_ID,
    location=REGION,
)

fs.list_entity_types() # It fails here


entity_type = fs.get_entity_type(entity_type_id="my_entity_type_id")
entity_type.list_features() # It also fails here
```

#### Stack trace
```
InvalidArgument: 400 List of found errors:	1.Field: parent; Message: The provided location ID doesn't match the endpoint. The valid location ID is `us-central1`.	 [field_violations {
  field: "parent"
  description: "The provided location ID doesn\'t match the endpoint. The valid location ID is `us-central1`."
}
]
```

I'm going to drop a PR to solve this issue. 

Thanks in advance!!

### PR DESCRIPTION
**Pull request by MichaelisTrofficus**
Fixes #1684

This PR fixes the issue reported in #1684, in particular, method `list_entity_types` and `list_features` .

### CODE REVIEW

**Comment by rosiezou** [comment]
@nayaknishant can you review this? I took a quick glance at the code and the `list` method is actually being invoked via the `EntityType.list` method in the SDK. `EntityType` inherits from `VertexAiResourceNounWithFutureManager` so it should be able to infer `project` and `location`, specifically based on this block here:
```
        list_request = {
            "parent": parent
            or initializer.global_config.common_location_path(
                project=project, location=location
            ),
        }
```
I would also recommend looking into the implementation of the `full_resource_name` helper function to make sure it's doing the right thing.

**Comment by nayaknishant** [comment]
Thanks Rosie, for looking into this. @MichaelisTrofficus are you running `aiplatform.init(project=PROJECT_ID, location=REGION)` before creating your Feature Store? I think that should initialize the project and location properly as Rosie mentioned. But regardless, I don't see an issue with explicitly setting the project and location (either it'll pull from the resource itself or from the global variable). What do you think @rosiezou?

**Comment by MichaelisTrofficus** [comment]
Hi @nayaknishant, in this particular example, I wasn't using aiplatform.init() since I was just following a vertex sample about FeatureStore SDK. Nonetheless, I think it would be nice to add this changes so that I just need to instantiate the FeatureStore object, avoiding the aiplatform.init.

**Comment by MichaelisTrofficus** [comment]
@nayaknishant any updates regarding this PR?

**Comment by MichaelisTrofficus** [comment]
@nayaknishant, is there any problem with kokoro:force-run, I mean any of the tests are failing?

**Comment by nayaknishant** [comment]
Hey @MichaelisTrofficus sometimes unit tests will not run from external contribution, I'm just forcing the run. As for the fix, we're looking into different options.

**Comment by rosiezou** [comment]
This change doesn't need to be merged in. Developers are encouraged to use `aiplatform.init(...)` to set global configs for project & location since it'll facilitate the rest of the development workflow. It will also resolve the error that you're seeing. Otherwise you will have to manually pass in project and location for most other SDK function calls pertaining to getting or creating resources.

**Pull request closed without merging**
