### PR TITLE
fix: bumping fastapi version to bypass a security flaw. See Issue 4273

### LINKED ISSUE #4273: Bumping fastapi version from 109.1  to  109.2 or greater
Hey, would it be possible to bump the fastapi version from 109.1 to 109.2 or greater? Version 109.1 requires starlette<0.36.0,>=0.35.0, which carries a security vulnerability.  Fastapi >=109.2 uses starlette>=0.36.3,<0.37.0, which is perfect because the starlette vulnerability got corrected in version 36.2.

https://github.com/fastapi/fastapi/compare/0.109.1...0.109.2
https://github.com/fastapi/fastapi/pull/11086
https://github.com/fastapi/fastapi/pull/11266

### PR DESCRIPTION
**Pull request by mnmelton-int**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-aiplatform/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)
- [ ] Get the necessary approvals
- [ ] Once the last commit on the PR has been approved, add the "ready to pull" label to the Pull Request

Note: do not merge your PR from GitHub. Adding the "ready to pull" label is the final step in the review process.
After approvals, the changes in your PR will be committed to the `main` branch and this PR will be closed.

Fixes #4273  🦕

### CODE REVIEW

**Comment by mnmelton-int** [comment]
This PR doesn't have to be the one that's merged, but the dependency changes do need to be made. We're running into deployment issues, because of the security flaws listed in the linked issue.

**Comment by mnmelton-int** [comment]
@Ark-kun LWould you mind making sure that the changes get made in the main repo? Thanks.

**Comment by Ark-kun** [comment]
@mnmelton-int Hello. Thank you for your PR. Can you please sign the CLA? It's a pretty simple process.

**Comment by mnmelton-int** [comment]
Cool beans, everything is signed. Let me know if there's anything else that I need to do. Also let me know if there needs to be some buffer time to test out these dependency changes.

**Comment by mnmelton-int** [comment]
Any update on this @Ark-kun? We're in a holding pattern until this is merged.

**Review by Ark-kun — APPROVED** [review]

**Review by Ark-kun — APPROVED** [review]

**Comment by Ark-kun** [comment]
@mnmelton-int It looks like this version combination conflicts with TensorFlow:

See the pip error logs: https://btx.cloud.google.com/invocations/040d2a09-00ad-4f25-a90d-95579c19378d/log
```
The conflict is caused by:
    tensorflow 2.13.0 depends on typing-extensions<4.6.0 and >=3.6.6
    fastapi 0.111.0 depends on typing-extensions>=4.8.0
    tensorflow 2.13.0 depends on typing-extensions<4.6.0 and >=3.6.6
    fastapi 0.110.3 depends on typing-extensions>=4.8.0
    tensorflow 2.13.0 depends on typing-extensions<4.6.0 and >=3.6.6
    fastapi 0.110.2 depends on typing-extensions>=4.8.0
    tensorflow 2.13.0 depends on typing-extensions<4.6.0 and >=3.6.6
    fastapi 0.110.1 depends on typing-extensions>=4.8.0
    google-cloud-aiplatform[testing] 1.64.0 depends on starlette>=0.37.1
    fastapi 0.110.0 depends on starlette<0.37.0 and >=0.36.3
```

https://github.com/tensorflow/tensorflow/issues/61848

**Comment by mnmelton-int** [comment]
That should resolve the issue with that one dependency. I'll keep an eye out to see if more crop up.

**Review by kthytang — APPROVED** [review]

**Comment by mnmelton-mcmlops** [comment]
@Ark-kun could you add the kokoro:force-run label to the repo so the tests will run?

(Also this is the same person as @mnmelton-int, I finally got full access to my org related github account again 😭 )

**Comment by mnmelton-mcmlops** [comment]
Since this was too far of a bump for TF & lower python levels I reverted the dependencies back to where they were andj ust removed the fast api topside constraint of <=0.109.1

**Review by yinghsienwu — APPROVED** [review]

**Comment by mnmelton-mcmlops** [comment]
Let me know if there's anything else that I should do. I don't have merge capability under @mnmelton-int,  so I'll leave it to everyone here to merge it when ready. Just keep me posted so that I can alert my team. Thanks!

**Review by matthew29tang — APPROVED** [review]
I think it's safer to keep an upper bound that allows 0.109.2 (for the security fix) instead of removing it altogether. Keeping the lower bound will allow our system tests to still pass.

Approving this PR, but let's have an internal contributor add the <=0.109.2 upper bound as a fast-follow item to make it into this release.

**Comment by mnmelton-mcmlops** [comment]
Okay great that works for me. Can we bump that version to 0.114.0?  Just for peace of mind on our end?

**Review by yinghsienwu — APPROVED** [review]

**Comment by Ark-kun** [comment]
>Approving this PR, but let's have an internal contributor add the <=0.109.2 upper bound as a fast-follow item to make it into this release.

Should probably be `<1.0.0`

**Comment by mnmelton-mcmlops** [comment]
I'm happy with either option. 👍

**Comment by matthew29tang** [comment]
Merged in with https://github.com/googleapis/python-aiplatform/commit/b8a8cf2bf7166bf43166b9ef4b593ce2c8004f46

and https://github.com/googleapis/python-aiplatform/commit/2fe7552d4253ac2e2a1217adb9e32ced563133d7

Released in https://github.com/googleapis/python-aiplatform/releases/tag/v1.66.0

**Comment by mnmelton-mcmlops** [comment]
Awesome, I'll go ahead and close this PR

**Comment by abarone-btf** [comment]
This now happens with starlette and the latest version of the library

**Pull request closed without merging**
