### PR TITLE
feat: adding Python 3.10 support + updating google-vizier version

### PR DESCRIPTION
**Pull request by nayaknishant**
Hey @parthea, I think we're ready to support Python version 3.10 (TensorFlow now supports Python 3.10). Is there more to do for 3.10 support other than adding the extra line to `setup.py` (I'm assuming this change will automatically update the related files) or will I need to manually add to `CONTRIBUTING.rst`, `noxfile.py`, and `owlbot.py` (according to https://github.com/googleapis/python-aiplatform/pull/831)?

Thanks,
Nishant

### CODE REVIEW

**Comment by nayaknishant** [comment]
It seems like I have to manually add in the changes, I'll do that now.

**Comment by nayaknishant** [comment]
Thanks @parthea. I'm now running into a 3.10 unit test issue:
```
ERROR: Could not find a version that satisfies the requirement pytype==2022.3.8 (from google-vizier) (from versions: 2018.5.14, 2018.5.15, 2018.5.22, 2018.5.22.1, 2018.6.5, 2018.6.15, 2018.6.18, 2018.6.19, 2018.7.13, 2018.8.10, 2018.9.7, 2018.9.7.1, 2018.9.18, 2018.9.19, 2018.9.25, 2018.9.26, 2018.10.30, 2018.11.6, 2018.12.11, 2018.12.21, 2019.1.18, 2019.1.30, 2019.2.13, 2019.3.1, 2019.3.8, 2019.3.15, 2019.3.21, 2019.3.27, 2019.4.2, 2019.4.2.1, 2019.4.5, 2019.4.12, 2019.4.19, 2019.4.26, 2019.5.6, 2019.5.8, 2019.5.15, 2019.5.24, 2019.5.31, 2019.6.21, 2019.6.28, 2019.7.11, 2019.7.26, 2019.7.30, 2019.8.9, 2019.8.29, 2019.9.6, 2019.9.17, 2019.10.17, 2019.11.27, 2019.12.6, 2019.12.17, 2020.1.7, 2020.1.8, 2020.1.24, 2020.2.6, 2022.4.15, 2022.4.22, 2022.4.26, 2022.5.5, 2022.5.10, 2022.5.19, 2022.6.6, 2022.6.14, 2022.6.23, 2022.6.30, 2022.7.18, 2022.7.26, 2022.8.3, 2022.8.17, 2022.8.23, 2022.8.30)
ERROR: No matching distribution found for pytype==2022.3.8
```

**Comment by nayaknishant** [comment]
@halio-g any insight on this error? I think it's related to the google-vizier package for Python 3.10

**Review by parthea — APPROVED** [review]

**Review by halio-g — APPROVED** [review]
LGTM for the Vizier change

**Review by rosiezou — APPROVED** [review]

**Pull request merged**
