### PR TITLE
chore: Check in service proto file

### LINKED ISSUE #1173: Check in match service definition
Check the service definition in

google/cloud/aiplatform/_matching_engine/match_service.proto

so it is easy to access

### PR DESCRIPTION
**Pull request by yan283**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-aiplatform/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #1173  🦕

### CODE REVIEW

**Comment by ivanmkc** [comment]
The proto looks good but what was the rationale to not just add a match method for `IndexEndpointServiceClient`?

**Comment by yan283** [comment]
Match is a method of MatchService, not IndexEndpointService.  I assume that means it should not be part of IndexEndpointServiceClient?

**Comment by ivanmkc** [comment]
Sorry, I mean MatchService. Will there be a GAPIC version of MatchService?

**Comment by yan283** [comment]
This is a short term solution to make it easy for clients to generate their own library.   We are looking into operations to publish GAPICs in the long run.

**Comment by ivanmkc** [comment]
As discussed, please move to the _proto folder after https://github.com/googleapis/python-aiplatform/pull/1192 is merged.

**Comment by ivanmkc** [comment]
Hi @yan283, the matching engine PR is merged so you can move the proto to the google/cloud/aiplatform/matching_engine/_protos folder.

**Review by ivanmkc — APPROVED** [review]
LGTM

**Pull request merged**
