### PR TITLE
fix: Remove packaging package upper bound

### LINKED ISSUE #2004: Remove cautionary pin of packaging package
**Is your feature request related to a problem? Please describe.**
 Yes, the pin of the packaging package is conflicting with a lot of other google packages preventing new versions of related packages from being installed.
 
 **Describe the solution you'd like**
 I'd like to remove the upper bound on the packaging package.
 
 According to https://github.com/googleapis/python-aiplatform/pull/1398 it was added out of caution not out of a specific issue.
 
 **Describe alternatives you've considered**
n/a

 **Additional context**
n/a

### PR DESCRIPTION
**Pull request by r-richmond**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-aiplatform/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)
- [x] Get the necessary approvals
- [x] Once the last commit on the PR has been approved, add the "ready to pull" label to the Pull Request

Note: do not merge your PR from GitHub. Adding the "ready to pull" label is the final step in the review process.
After approvals, the changes in your PR will be committed to the `main` branch and this PR will be closed.

Fixes #2004 🦕

### CODE REVIEW

**Comment by nayaknishant** [comment]
Hi @r-richmond, could you add "fix: ..." in the beginning of the title so it follows conventional commits. Thanks for opening this PR!

**Comment by r-richmond** [comment]
@nayaknishant done

**Comment by r-richmond** [comment]
@nayaknishant got it to go through

**Comment by r-richmond** [comment]
@nayaknishant anything else needed here, looks all the tests passed.

**Comment by nayaknishant** [comment]
Thanks @r-richmond!

**Review by nayaknishant — APPROVED** [review]

**Comment by r-richmond** [comment]
@nayaknishant should I rebase the branch on main or are we waiting for something else?

**Comment by proteusvacuum** [comment]
Hello! We'd be interested in seeing this change go through too, as this currently conflicts with the latest version of the `black` package. Thanks!

**Comment by r-richmond** [comment]
I rebased onto main in the hopes that @nayaknishant will be able to merge soon

**Review by nayaknishant — APPROVED** [review]

**Review by nayaknishant — APPROVED** [review]

**Review by nayaknishant — APPROVED** [review]

**Comment by nayaknishant** [comment]
Hi @r-richmond, thanks for your patience! Your PR has been merged in here: https://github.com/googleapis/python-aiplatform/commit/73011c01013149690e413e1f8b1b68eb5169fedf.

**Comment by nayaknishant** [comment]
We plan on having a patch release next week 👍

**Comment by ajrheaume** [comment]
Any update on when this patch is scheduled to be released?

**Pull request closed without merging**
