### PR TITLE
feat: adds enhanced protos for time series forecasting

### PR DESCRIPTION
**Pull request by parthea**
This PR migrates from autosynth to [owl bot](https://github.com/googleapis/repo-automation-bots/tree/master/packages/owl-bot).  owl bot will save time for maintainers as it will automatically open PRs when there are updates in [googleapis-gen](https://github.com/googleapis/googleapis-gen/tree/master/google) without requiring maintainers to run `synthtool` to build the client from protos. Additionally, similar to autosynth, PRs will be automatically opened when there are template updates. 

Googlers see [here](http://go/owlbot-user-guide).

This PR also pulls in the latest API changes from googleapis-gen and synthtool templates.

This PR includes the following features/fixes/doc updates.

chore: migrate to owl bot
docs: removes tinyurl links
docs: changes product name to Vertex AI
docs: correct link to fieldmask 
feat: adds enhanced protos for time series forecasting 
fix: remove display_name from FeatureStore
feat: add invalid_row_count to ImportFeatureValuesResponse and ImportFeatureValuesOperationMetadata
feat: add featurestore, index, metadata, monitoring, pipeline, and tensorboard services to aiplatform v1beta1
fix: configuring timeouts for aiplatform v1 methods 
feat: remove unsupported accelerator types
feat: add aiplatform API Vizier service
feat: removes forecasting (time_series_forecasting proto) from public v1beta1 protos
chore: updates copyright on schema/ protos
chore: updates prediction and training proto files to v1beta1 AI Platform client libraries.
feat: removes unused protos from schema/ folders: schema/io_format.proto, schema/saved_query_metadata.proto
feat: ImageSegmentationPredictionResult.category_mask field changed to string data type
feat: AutoMlImageSegmentationInputs.ModelType adds MOBILE_TF_LOW_LATENCY constant
feat: AutoMlVideoClassificationInputs.ModelType adds MOBILE_JETSON_VERSATILE_1 constant
fix: add async client to %name_%version/init.py
chore: add autogenerated snippets
chore: remove auth, policy, and options from the reserved names list
feat: support self-signed JWT flow for service accounts
chore: enable GAPIC metadata generation
chore: sort subpackages in %namespace/%name/init.py

### CODE REVIEW

**Comment by busunkim96** [comment]
This repository maintains long-running development branches. Will it be easier to apply this change to move some other branch to owlbot first?

@vinnysenthil could you advise us on the best course of action? Thanks!

go/owlbot-howto explains Owl Bot which is replacing synth.py/Autosynth.

**Review by aribray — APPROVED** [review]

**Comment by parthea** [comment]
@aribray Please take a look at the conventional commit messages in the PR body to check whether any of the changes should be considered breaking.

**Comment by busunkim96** [comment]
@parthea Are any those breaking changes in the v1beta1? I think the `!` should be dropped from those messages to avoid creating a  2.0.0 release.

**Comment by parthea** [comment]
@busunkim96 I have a concern that some changes in v1 might be breaking. For example, see https://github.com/googleapis/googleapis-gen/commit/2ccb81a5a98312aa585b46fc6264ad2d64685c24#diff-f05c030e331b4418a0a9bb9d3cd01d22be4aceab3db18aec1d9660059d590ae0R1592 where a test was changed. 

It looks like [nodejs-ai-platform](https://github.com/googleapis/nodejs-ai-platform/pull/124) acknowledged the breaking change in the changelog but did not bump the major version in the [next release 1.7.0](https://github.com/googleapis/nodejs-ai-platform/pull/125). 

I'd like to hand this over to @aribray and @telpirion to take a look at the history for [aiplatform v1](https://github.com/googleapis/googleapis-gen/commits/master/google/cloud/aiplatform/v1/aiplatform-v1-py) since February 5th and confirm that none of the changes are breaking. The reason that the date is February 5th, 2021 is because of the [sha](https://github.com/googleapis/python-aiplatform/blob/master/synth.metadata#L14) in synth.metadata here.

**Comment by parthea** [comment]
After digging into the CL with the breaking change, there is messaging that suggests the changes should not be breaking so everything looks good on my end. I'll remove the exclamation point `!` and merge.

**Pull request merged**
